# Generated by Django 5.1.4 on 2025-01-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('region', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='GovernorRegion',
            new_name='Governor',
        ),
        migrations.AlterModelOptions(
            name='regionstatistics',
            options={'ordering': ['uuid']},
        ),
    ]
