# Generated by Django 5.1.4 on 2025-01-05 07:23

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('neighborhood', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('house_boss', models.CharField(max_length=200)),
                ('house_number', models.PositiveIntegerField()),
                ('a_b', models.CharField(choices=[('A', 'A'), ('B', 'B')], max_length=200)),
                ('status', models.CharField(choices=[('POORER', 'POORER'), ('MIDDLE', 'MIDDLE'), ('RICH', 'RICH')], max_length=200)),
                ('people', models.PositiveIntegerField(blank=True, default=5)),
                ('area_kv_m', models.DecimalField(decimal_places=2, default=415.5, max_digits=15)),
                ('neighborhood', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='house', to='neighborhood.neighborhood')),
            ],
            options={
                'ordering': ['house_number', 'a_b'],
            },
        ),
        migrations.CreateModel(
            name='HouseStatistics',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('education_high', models.PositiveIntegerField(default=0, verbose_name="Oliy ta'lim olganlar")),
                ('education_middle', models.PositiveIntegerField(default=0, verbose_name="O'rta ta'lim olganlar")),
                ('no_education', models.PositiveIntegerField(default=0, verbose_name="Ta'lim olmaganlar")),
                ('electricity_available', models.BooleanField(default=False, verbose_name='Elektr energiyasi mavjudligi')),
                ('water_available', models.BooleanField(default=False, verbose_name="Suv ta'minoti mavjudligi")),
                ('gas_available', models.BooleanField(default=False, verbose_name="Gaz ta'minoti mavjudligi")),
                ('house', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='house.house', verbose_name='Uy')),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
    ]
