# Generated by Django 5.1.4 on 2025-01-05 07:23

import django.db.models.deletion
import shortuuid.django_fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('MFY', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Neighborhood',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('title', models.CharField(max_length=200)),
                ('elder', models.CharField(default='Jhon Doe', max_length=250)),
                ('area_km_kv', models.DecimalField(decimal_places=2, default=4.65, max_digits=15)),
                ('houses', models.PositiveIntegerField(default=85)),
                ('people', models.PositiveIntegerField(default=530)),
                ('MFY', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='MFY.mfy')),
            ],
            options={
                'ordering': ['-uuid'],
            },
        ),
        migrations.CreateModel(
            name='NeighborhoodStatistics',
            fields=[
                ('uuid', shortuuid.django_fields.ShortUUIDField(alphabet='abcdefghijklmnopqrstuvwxz123456789', editable=False, length=22, max_length=12, prefix='', primary_key=True, serialize=False)),
                ('created', models.DateField(auto_now_add=True)),
                ('population_density', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name='Aholi zichligi (kishi/km²)')),
                ('unemployment_rate', models.DecimalField(decimal_places=2, default=0.0, max_digits=5, verbose_name='Ishsizlik darajasi (%)')),
                ('avg_income', models.DecimalField(decimal_places=2, default=0.0, max_digits=10, verbose_name="O'rtacha daromad (so'm)")),
                ('young_population', models.PositiveIntegerField(default=0, verbose_name='Kichik yoshdagi aholi (0-14)')),
                ('working_population', models.PositiveIntegerField(default=0, verbose_name='Ishchi yoshdagi aholi (15-64)')),
                ('elderly_population', models.PositiveIntegerField(default=0, verbose_name='Keksaygan yoshdagi aholi (65+)')),
                ('education_high', models.PositiveIntegerField(default=0, verbose_name="Oliy ta'lim olganlar")),
                ('education_middle', models.PositiveIntegerField(default=0, verbose_name="O'rta ta'lim olganlar")),
                ('no_education', models.PositiveIntegerField(default=0, verbose_name="Ta'lim olmaganlar")),
                ('good_houses', models.PositiveIntegerField(default=0, verbose_name='Yaxshi sharoitdagi uylar')),
                ('average_houses', models.PositiveIntegerField(default=0, verbose_name="O'rta sharoitdagi uylar")),
                ('poor_houses', models.PositiveIntegerField(default=0, verbose_name='Yomon sharoitdagi uylar')),
                ('neighborhood', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='statistics', to='neighborhood.neighborhood', verbose_name='Mahalla')),
            ],
            options={
                'ordering': ['uuid'],
            },
        ),
    ]
